#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//my moving backward(reverse) with subroutines, by Professor Reed
//10JAN2016
//

/*------------------------------------------------------------------------------------------------
  This program will move your robot in reverse for 2 seconds. At the end of the program, all
  motors will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    MotorC        	leftMotor           LEGO EV3 Motor		      Left side motor
    MotorB       	rightMotor          LEGO EV3 Motor		      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/
//
//==================================
/* my moving in reverse subroutine
====================================
*/
//
int movingINreverse(int motrSpeedVal)
{
	setMotorSpeed(leftMotor,  -motrSpeedVal);		//Set the leftMotor (motor1) to half power reverse (-50)
	setMotorSpeed(rightMotor, -motrSpeedVal);   //Set the rightMotor (motor6) to half power reverse (-50)
	sleep(2000);
	//Wait for 2 seconds before continuing on in the program.
	return(0);

}//end of moving In Reverse
//
//
//================================================
/* task main() for my moving in reverse subroutine
==================================================
*/
//
task main()
{
	int motrSpeedVal = 50;
	movingINreverse(motrSpeedVal); // call moving IN Reverse with speed value
		
}// ###end of task main -- moving in reverse Demo Pgm###
