#pragma config(StandardModel, "EV3_REMBOT")
// #pragma must be the first line(s) of code.
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//myMovringForward.c Program, by ProfJRR -- 10JAN2016
//
//Now with subroutines

/*------------------------------------------------------------------------------------------------
  This program will move your robot forward for 2 seconds. At the end of the program, all motors
  will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    MotorC        			leftMotor           LEGO EV3 Motor		      Left side motor
    MotorB       				rightMotor          LEGO EV3 Motor		      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/
int myMoveFWD(int mveFWDval)
{
	setMotorSpeed(leftMotor,  mveFWDval);		//Set the leftMotor (motor1) to half power (50)
	setMotorSpeed(rightMotor, mveFWDval);  //Set the rightMotor (motor6) to half power (50)
	sleep(2000);
	//Wait for 2 seconds before continuing on in the program.
	return(0);
}

//
//
//
task main()
{
	
	int mveFWDval = 50;

	myMoveFWD(mveFWDval);
 

}// end of task main()
