#pragma config(StandardModel, "EV3_REMBOT")
//my point turns, Professor Reed
//10JAN2016
//
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will have your robot make a right point turn for one (1) second and then make a
  left point turn afterwards. At the end of the program, all motors will shut down automatically
  and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    MotorC        			leftMotor           LEGO EV3 Motor		      Left side motor
    MotorB       				rightMotor          LEGO EV3 Motor		      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/
//===========================
//let's turn right subroutine
//===========================
int turnRHT(int motorPWR)
{
	setMotorSpeed(leftMotor, -100);		//Set the leftMotor (motor1) to full power reverse (-100)
	setMotorSpeed(rightMotor, 100);  	//Set the rightMotor (motor6) to full power forward (100)
	sleep(1000);
	return(0);
}// end of turnRHT subroutine
//
//===========================
//let's turn left subroutine
//===========================
int turnLFT(int motorPWR)
{
  setMotorSpeed(leftMotor, 100);		//Set the leftMotor (motor1) to full power forward (100)
	setMotorSpeed(rightMotor, -100);  //Set the rightMotor (motor6) to full power reverse (-100)
	sleep(1000);	
	return(0);
}// end of turnLFT subroutine
//	
//============================
//task main() for turns
//============================
//
task main()
{
int	motorPWR = 0;
//
//let's turn right!
turnRHT(motorPWR);		
//
//let's turn left!
turnLFT(motorPWR);
//
}//end of task main()
