//LOCATED AT: GitHub==> profjrr/Profjrr_OETC_RoboticsWorkshop_2016

//Create Object Avoidance with Subroutines (PROJECT 02)
//with errors!!!

//Again, proper Computer Program Construction in ROBOTC
//shows main() task and subroutine usage
//with liberal comments as appropriate

//Modified by Professor Reed, Feb. 2nd, 2015
//On 08JAN2016 for Robotic Workshop OETC 2016

//Removed #pragma's
//motorLeft  is now motorB
//motorRight is now motorC
//
//#pragma config(Sensor, S4,              sonar4,        sensorEV3_Ultrasonic)
//#pragma config(Motor,  motorB,          motorLeft,     tmotorEV3_Large, PIDControl, encoder)
//#pragma config(Motor,  motorC,          motorRight,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//
//global variables:
int currentDistance = 0;
const int distanceToMaintain = 30;
//

void operateSonicDetector()
{
// Read the sensor
		currentDistance = SensorValue[S4];
		displayCenteredBigTextLine(4, "Dist: %3d cm", currentDistance);

		// We're too far away, move forward
		if ((distanceToMaintain - currentDistance) < -2)
		{
			motor[motorA] = 30;
			motor[motorC] = 30;
		}
		// We're too close, move backwards
		else if ((distanceToMaintain - currentDistance) > 2)
		{
			motor[motorB] = -30;
			motor[motorC] = -30;
		}
		// We're good, don't go anywhere
		else
		{
			motor[motorB] = 0;
			motor[motorC] = 0;
		}
}//end of operateSonicDetector routine
//
task main()
{
	// Distance to maintain to the target (30 cm)

	while(true)
	{
		operateSoncDetector(); //test if too far or too close or don't move!

		//Loop to monitor value in Sensor debugger window
		sleep(50);
	}//end of while loop to run EV3

}// end of task main()
