//LineFollower -- Project01 -- OETC 2016 Robotics Workshop -- Prof.JRR
//Feb. 9th, 2016
//linefollower now with subroutines and clean program design!!!
//
//
//NOT using #pragma!
//#pragma config(Sensor, S3,              ev3color,       sensorEV3_Color)
//#pragma config(Sensor, S4,              sonarev3,       sensorEV3_Ultrasonic, modeEV3Ultrasonic_Inch)
//#pragma config(Motor,  motorB,          leftMotorB,    tmotorCV3_Large, PIDControl, driveLeft, encoder)
//#pragma config(Motor,  motorC,          rightMotorC,   tmotorCV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//
//Modified by Professor Reed, Feb. 6th, 2015
//

int setMotorBroutine(int setmotval)
{
	//printf("set Motor B\n")
		motor[motorB] = setmotval;
    return(motor[motorB]);
}// end of setMotorB routine
//
int setMotorCroutine(int setmotval)
{
		motor[motorC] = setmotval;
    return(motor[motorC]);
}// end of setMotorC routine
//
//
task main()
{
  int setmotval = 0;
	int threshold = 11; //45 light sensor threshold
	int mValue    = 40; //40 motor value?
//
	setMotorBroutine(setmotval);
	setMotorCroutine(setmotval);
//
	while(true){
		if((SensorValue(S3) > threshold) && (SensorValue(S3)<=100))
		{
			motor[motorB] = mValue;
			motor[motorC] = 0;

		}
		else
		{
			motor[motorB] = 0;
			motor[motorC] = mValue;
			//turnRight(2, degrees, 18);
		}

	}// end of while loop()

}// end task main()
//
